### PR TITLE
let the logo link to the Elm homepage

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Otherwise, at the moment there seems to be no way to navigate from the packages catalog pages to the actual Elm homepage.

### CODE REVIEW

**Comment by mgold** [comment]
Navigation definitely needs to be improved, but it's going to take a bit more work. The new home page lists "All Packages" and "Core Libraries" prominently. We also want to be able to link back to said home page. Currently it's not obvious that "Packages" takes you to the listing but the tangram takes you home. So:
* Tangram takes you to elm-lang.org, and maybe turns the elm colors on mouseover.
* Home (or Main) takes you to package.elm-lang.org
* All Packages and Core Libraries take you to the same pages as on the home page.

**Comment by jvoigtlaender** [comment]
Yes, these proposals sound good. I have no idea how the "tangram turns the elm colors on mouseover" can be done, though.

**Comment by jvoigtlaender** [comment]
Maybe it would be enough to let the logo have these colors to begin with. That might be enough of an indicator (due to the contrast to the colors of the rest of the page) that something interesting waits there.

**Comment by evancz** [comment]
I think things ended up looking odd with the properly colored logo, but I like the links you describe.

@laszlopandy also suggested the "Libraries" tab on the main site be renamed to "Reference" or something like that and link directly to package.elm-lang.org.

I'd also like to have some way to search that is biased by github stars or recent downloads. We tried to do a general drop-down thing in the top bar, but ran into too many issues. A good first draft might be a dedicated page, so we'd have Home, Packages, Core, Search or something like that?

**Comment by jvoigtlaender** [comment]
I again stumbled upon the strangeness that there seems to be *no* link whatsoever going from the whole http://package.elm-lang.org/ site to http://elm-lang.org/

Shouldn't some such link be added, irrespective of above design discussions? It need not be so fancy. It just needs to be there.

**Comment by jvoigtlaender** [comment]
Closing this PR, due the reasoning outlined [here](https://github.com/elm-lang/elm-lang.org/issues/351#issuecomment-130016308). (I checked the situation for Haskell and Hackage, and to my astonishment it is the same there like described by Evan for Rust.)

**Pull request closed without merging**
