### PR TITLE
Add warning on pages for outdated package versions

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Addresses issues like in [this thread](https://groups.google.com/d/msg/elm-discuss/LOPrOdrDXTQ/pFcGkMOaxNUJ).

### CODE REVIEW

**Comment by mgold** [comment]
Would it be possible to link to the latest version?

**Comment by jvoigtlaender** [comment]
Sure, though I don't really see the point, since the drop-down box with all the versions will be right next to that message anyway.

Also, while on a main package page like http://package.elm-lang.org/packages/Apanatshka/elm-list-ndet/1.0.1 it is clear what you want to link to as "latest version", namely http://package.elm-lang.org/packages/Apanatshka/elm-list-ndet/latest, it is not so clear on a module page, like http://package.elm-lang.org/packages/Apanatshka/elm-list-ndet/1.0.1/List-NDet. What do you want to link to there? http://package.elm-lang.org/packages/Apanatshka/elm-list-ndet/latest/List-NDet? What if the latest version (say, 2.0.0) of that package does not even have a `List-NDet` module anymore? Do you really then want to have a dead link there? (As a side point, I don't know what using the drop-down menu would give you in such a case.)

In any case, it doesn't make sense for me to revise the pull request to include additional behavior if it's not clear @evancz wants anything done about this "someone stumbles on outdated doc pages without noticing" issue at all.

**Comment by evancz** [comment]
Hey, somehow I missed this the first time around. Can you take a screenshot of how it looks? Otherwise, I'm on board with clearly marking this. Perhaps the ideal version is, "The latest version of this package is ____" with a link you can click real easy. This is something I'd like from Hackage actually.

**Comment by jvoigtlaender** [comment]
I'm afraid I can't easily do a screenshot, since I haven't built the package repository locally.

That said, I guess it's quite obvious how it will look? Below the "big words" making up the package path, like "elm-lang / core / Array", there will be normal sized text "You are not looking at the documentation for the latest version of this package!".

About providing a link: The idea would be to always link to the entry page of the latest version of the package? So that even if one is looking at http://package.elm-lang.org/packages/Apanatshka/elm-list-ndet/1.0.1/List-NDet but that is not the latest version, one doesn't get a link to http://package.elm-lang.org/packages/Apanatshka/elm-list-ndet/latest/List-NDet, but instead to http://package.elm-lang.org/packages/Apanatshka/elm-list-ndet/latest? That should be easily accomplished, yes.

**Comment by jvoigtlaender** [comment]
Okay, added creation of a link to the latest version of the package.

**Comment by jvoigtlaender** [comment]
BTW, concerning your wishing that Hackage did that: supposedly [this Crome extension](https://chrome.google.com/webstore/detail/hackage-fu/dnpldbohleinhdgfnhlkofpgkdcfcfmf) gives you the desired behavior on Hackage.

**Comment by jvoigtlaender** [comment]
Here's a screenshot of how this now looks:
note
The "2.1.0" in the last line will be a link (in this case) to http://package.elm-lang.org/packages/elm-lang/core/2.1.0

**Comment by jvoigtlaender** [comment]
@evancz, this is ready to go.

**Comment by evancz** [comment]
Thanks a lot for working on this, it should be live on the site now! I made some minor style tweaks to the code and the visuals, but everything is lookin' good!

**Pull request merged**
