### PR TITLE
Match union tags when searching a package

### LINKED ISSUE #112: Reinstate feature: Enable search for constructor names
[This feature](https://github.com/elm-lang/package.elm-lang.org/pull/74#issue-102508282) worked on `master`, but got lost during the `revamp`.

### PR DESCRIPTION
**Pull request by mgold**
This fixes #112.

Component.PackageSidebar.SearchDict's values are now pairs of strings. The first is the name to display and the second is the name to link to. In most cases these are the same, but union tags are displayed as themselves but link to the name of their parent type. `toSearchDict` learns how to find union tags from entries. Most of the other changes in this module is propagating that logic down to where the links are actually rendered.

@evancz - I'm sure you'll need to reformat a few things to your liking, but I hope the scope of the changes are okay.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
This doesn't handle the cases from [this comment](https://github.com/elm-lang/package.elm-lang.org/issues/112#issuecomment-158496114) like the previous implementation did, right? I think it would be better it did.

**Comment by mgold** [comment]
Was already working on it! The only thing it removes are tags with the same name as the type, i.e. when you'd have two links with the same name *and* destination, because I agree that's silly. Other duplicates are kept.

**Comment by jvoigtlaender** [comment]
Yes, that's how it was previously accepted into master.

**Comment by mgold** [comment]
I thought of a better way to do this that localizes changes to the view module and doesn't change any types that other modules rely on. I've force-pushed it and edited the top description.

**Comment by evancz** [comment]
Alright, this is merged in. It looks like it does not close PRs automatically if they get merged in separately, but this is added. Thanks for the improvement! And sorry @jvoigtlaender for not getting support translated over myself in the initial release!

**Pull request closed without merging**
