### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by ianbollinger**
Remove unused package dependencies from `run-server.cabal`.

### CODE REVIEW

**Comment by evancz** [comment]
And you were able to successfully build the executable after these changes?

**Comment by ianbollinger** [comment]
I found nothing via grep:

```
grep -e "Set" -e "Map" -e "Seq" -e "Tree" -e "Graph" backend/*
backend/Compile.hs:          Left (concatMap toString errors)
backend/Main.hs:-- | Set up the reactor.
```

**Comment by ianbollinger** [comment]
Indeed; both run-server and upgrade-docs.

**Comment by ianbollinger** [comment]
Indeed; both run-server and upgrade-docs.

**Comment by evancz** [comment]
What are you running to detect this?

**Comment by ianbollinger** [comment]
I'm using [packunused](https://hackage.haskell.org/package/packunused).

**Pull request merged**
