### PR TITLE
Whitelist elm-community/elm-history

### PR DESCRIPTION
**Pull request by rgrempel**
The discussion for this change is at issue #122, and this thread in the forums:

https://groups.google.com/forum/#!topic/elm-discuss/-GQJkWGdMvg

So, over to @evancz for consideration.

### CODE REVIEW

**Comment by simonh1000** [comment]
This is pretty heavily used library, so it would be great to release this update to 0.16 (the same native code in practise as earlier versions)

**Comment by jvoigtlaender** [comment]
@evancz, just for clarity: The re-release of this package was already approved for whitelisting by three "eligible voters" over at #122. Merging of the whitelisting PR and then publishing the whitelist to http://package.elm-lang.org/ is still open.

**Comment by etaque** [comment]
Hi,
Also waiting, it's a bit sad to be blocked here. @evancz I understand you need to choose focus, couldn't you delegate those whitelisting merges?

**Comment by w0rm** [comment]
It's been a while, feeling kinda sad that basically bumping the version and transferring the ownership of the package takes so long (I counted two weeks). Maybe the whole process has to be reconsidered to be more efficient to not block the progress?

**Comment by evancz** [comment]
This is a known problem: https://github.com/elm-lang/package.elm-lang.org/issues/105

I haven't been watching these because the process does not really work, and I updated [the message](https://github.com/elm-lang/package.elm-lang.org/blob/master/src/backend/Routes.hs#L179-L203) to clarify what is going on for people.

Should be possible to publish now.

**Comment by w0rm** [comment]
@evancz cool, many thanks for this!

**Comment by rgrempel** [comment]
Thanks, this has now been published.

**Pull request merged**
