### PR TITLE
Add json and bash highlighting, and update to version 8.8.0 of highlight.js

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Supporting `json` highlighting makes sense since people may want to show `json` examples in their documentation (for example when talking about configuration).

Supporting `bash` highlighting makes sense since people may want to show shell instructions in their documentation (for example when talking about installation of library and/or tools).

Since I needed to download a new highlight.js "package" anyway, I also took the opportunity to upgrade it from 8.7 to the latest version 8.8.0.

Supported languages here now are: `bash`, `css`, `elm`, `javascript`, `json`, `haskell`, `xml` (which actually is mainly for `html` highlighting).

Keeping support for `haskell` highlighting makes sense, since old (and some recent) packages on http://package.elm-lang.org/ still use `haskell` code blocks instead of `elm` code blocks. Even if those actually contain what is meant to be Elm code, they will be displayed roughly okay, as long as `haskell` is kept as a highlight.js-supported language here.

### CODE REVIEW

**Comment by evancz** [comment]
I feel like it makes sense to drop haskell since there is a viable alternative and people should switch.

I think "the right thing to do" is to use the untagged blocks, where you just indent by four spaces. I'd want to push people in that direction as early as possible.

Does that make sense?

**Comment by jvoigtlaender** [comment]
Well, I was thinking about stuff like http://package.elm-lang.org/packages/elm-lang/core/1.0.0, which will lose its syntax highlighting if we drop `haskell`, because the code block there was switched to `elm` only in a later package version. But probably there will be not much need for people to look at old versions of packages. So yes, I'll drop `haskell`.

**Comment by jvoigtlaender** [comment]
Okay, dropped `haskell` (and squased the commits), so ready to merge.

**Comment by evancz** [comment]
Cool, thank you!

**Pull request merged**
