### PR TITLE
Link qualified type names to definitions, inside package (documentation)

### PR DESCRIPTION
**Pull request by jvoigtlaender**
The effect of this PR is as follows.

Consider the following documentation: http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.1/Signal-Stream#timestamp.

Currently it shows as:
was

After this PR it shows as (tested locally):
will
where the two occurrences of `Stream` are clickable links to http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.1/Signal-Stream#Stream and the occurrence of `Time` is a clickable link to http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.1/Signal-Time#Time.

Such links inside the documentation of a package have been requested several times.

### CODE REVIEW

**Comment by evancz** [comment]
This is exciting! I forked it onto my local copy and could not get it working. I am guessing I have some sort of state locked up in some build artifact. Will try again soon.

Thanks for working on this!

**Comment by jvoigtlaender** [comment]
When you say "could not get it working", what exactly does that mean? It compiled but you do not get to see links in the docs? If that, note that it depends on where you look. Within the `core` documentation, you won't see many links. The reason being that the types in there (in the `.json` files) are mostly unqualified (and see the PR's title: only qualified type names are claimed to turn into links). For example, http://package.elm-lang.org/packages/elm-lang/core/2.1.0/docs/Graphics-Input-Field.json contains the type string "Style -> (Content -> Signal.Message) -> String -> Content -> Element" for the name string "field". Only the "Signal.Message" part of this can turn into a clickable link. For the others, there's no way, of course. In other packages, you will see many more links, since the `.json` files contain more qualifiers.

Is that the issue? Then it is independent of this PR. Make sure that indeed there are qualified types everywhere in the docs files (as said [here](https://groups.google.com/d/msg/elm-discuss/7JJyM1UkXsQ/vRGGaKQMayAJ)), and the links will appear.

**Comment by jvoigtlaender** [comment]
BTW, I wonder whether one wouldn't want to replace `(Text.fromString ",")` by `(green ",")` in [this line](https://github.com/jvoigtlaender/package.elm-lang.org/blob/8e0687727c7e40f49730864aa5bea0be1ce98c27/frontend/Component/Documentation.elm#L304), so that commas in record types are turned green, like the equal signs and colons and function arrows and case seperators in union types already are throughout.

**Comment by evancz** [comment]
Okay, I figured out the problem! I had an older version of the packages tar, so when I looked at elm-signal-extras, I was looking at 5.1.1 not 5.2.1. Seems to be working with the new docs. Thanks again!

**Comment by jvoigtlaender** [comment]
Cool. What about my last minute comment that one might want the commas (in showing record types) to be turned green? That would be an easy fix, and correspond to how colons and arrows and case separators are shown.

**Comment by jvoigtlaender** [comment]
I've just the "turn commas green" stuff in https://github.com/elm-lang/package.elm-lang.org/pull/61. See whether you like it.

**Pull request merged**
