### PR TITLE
Preview package documentation on site

### PR DESCRIPTION
**Pull request by burabure**
# Motivation

A common request from package authors is "How can I see the docs before I publish my package?" Like in this issue https://github.com/elm-lang/elm-lang.org/issues/169.

My solution creates a "Preview your Documentation" page that takes a .json documentation file from elm-make via a file input, loads it locally using the js File API, parses it with the existing document parsers and displays the formatted documentation

# What I changed

- Added a new route for "tools/preview-documentation" on the server
- Added links to the tool in the Resources sidebar, API Design Guidelines and Documentation Format pages.
- Added list styles to the Resources sidebar to prevent confusion when reading 2+ text lines items
- Added a "tools" tag type  in ```Route.elm``` and displays text for the header in
- Created PreviewDocumentation.elm with the necessary logic for the tool
- Created an ```/assets/js/jsonLoader.js``` file to handle the needed native js File API logic
- Added ```new-packages.json``` to .gitignore because it seems to be a good idea ;D

I'm just learning Elm and I'd love any suggestions or feedback about the code, implementation or overall solution

### CODE REVIEW

**Comment by evancz** [comment]
Very excited for this, thanks! :D 

Can you do a [contributors agreement](https://github.com/elm-lang/elm-compiler/blob/master/ContributorAgreement.pdf) and send it to the email associated with my github?

**Comment by evancz** [comment]
Cool, got it!

I'm doing some reviewing now, but overall it's looking good. I'm just changing up some details. I'll get back to you when I know what is left!

**Comment by evancz** [comment]
Are you on twitter? Want to @ you when I announce this :)

**Comment by burabure** [comment]
yay! I'm @elburabure on twitter. I haven't done a blog in years, but maybe it'd be cool to talk about my experience diving into the codebase while learning elm =)

**Comment by evancz** [comment]
No pressure either way!

I did some refactoring to make it more Elm-y. I cc'd you on one of the changes, but you can also read https://github.com/elm-lang/package.elm-lang.org/commit/e36579c92e51fcd3e2f9f0145e5c920b1a1b4371 as a code review. Ideally we'd also stop reaching into the internal details of `PackageDocs` to do stuff (by making a clear public API for that module), but I didn't get to that.

**Comment by evancz** [comment]
Thanks for working on this, excited to release it! :D

**Comment by evancz** [comment]
Okay, this is live :)

**Comment by burabure** [comment]
awesome!, I'm reading through your commits. is it OK if I post a couple questions once I'm done reading the changes?

**Comment by evancz** [comment]
Sure, no problem :)

**Comment by burabure** [comment]
Wow, everything is really clear and explicit like you've said. I have to start diving into effects and tasks though, because they're still a bit alien to me.

Anyway, there's a small "bug" that I didn't get to solve; if you click on a type inside a doc entry it'll take you to a 404 because the current link generation isn't flexible enough to handle this implementation. To solve this we would have to copy and override some functions out of ```PackageDocs ``` and ```Entry```  into the preview logic. But like you've said I think it would be much better to define a clear API for ```PackageDocs ``` in order to prevent breaking dependencies in future versions.

I think i'll give it a try over the weekend =D

**Comment by evancz** [comment]
Interesting! If the all links could be "contextualized" that could help with a separate feature request. Folks sometimes ask for a local version of their docs, so they can browse them on a train or a plane or whatever other place does not have internet. One big issue is that all the links are absolute, which breaks when browsing HTML locally. I've also vaguely considered adding this to elm-reactor so that'd be the central home for exploring this stuff. So it may be cool if some "context" was passed in that determined how all the links looked.

I think it's safe to "ignore" this information, but perhaps it can help lead you to a framing of things that is flexible and nice. I'm not really sure how any of this will look, but more context can't hurt :)

**Comment by burabure** [comment]
I was actually thinking about something like that, so that use case info helps a lot =D

**Comment by jvoigtlaender** [comment]
@evancz, what do you mean by this:
> One big issue is that all the links are absolute, which breaks when browsing HTML locally.

When I originally implemented the "types link to their definition" feature, the links were not created as absolute links. Have you really changed that during the reimplementation of the feature in the `revamp` branch?

**Comment by evancz** [comment]
I believe most links are like `/package/elm-lang/core/3.0.0` which works on servers and localhost. But when you are reading from the file system, this tries to find the `packages/` directory in the deepest root on your computer.

**Comment by jvoigtlaender** [comment]
@evancz, I think you are talking about different links than @burabure and I.

@burabure was talking about:
> Anyway, there's a small "bug" that I didn't get to solve; if you click on a type inside a fn signature in a doc entry it'll take you to a 404

That's the "types link to their definition" feature I'm also talking about. These links are created strictly as relative links. For example, if you are on http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Date, and print a type signature `millisecond : Time`, the `Time` in there will cary a *relative* link, literally, "Time#Time". Yes, that will then turn into http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Time#Time, which is where one wants to go. But the link itself is just created as "Time#Time".

I don't really see why the preview documentation feature should not be able to accomodate this kind of links without major restructuring of the overall processing.

**Comment by burabure** [comment]
@jvoigtlaender I think you're right, we got a bit mixed up with those links.

Anyways I'll be tackling that bug over the weekend, and if you guys could point me to a simple issue that you need help with I would be happy to see what I can do also =)

**Comment by jvoigtlaender** [comment]
I think what it would take to fix the specific issue here would be to restructure the routes for the preview tool a bit. Where it currently uses route http://package.elm-lang.org/help/docs-preview#Module to show the documentation for `Module`, it should use route http://package.elm-lang.org/help/docs-preview/Module. Is that possible to achieve? Then, a relative link "OtherModule#TypeDef" would turn into http://package.elm-lang.org/help/docs-preview/OtherModule#TypeDef, which would exactly be what is needed to get linking to type definitions correct.

**Comment by burabure** [comment]
@jvoigtlaender sounds like a clean fix. Off the top of my head, the other option would be to extract the url generation logic out into its own module and make something like a link helper, which I guess could be useful in the future but also might be "overkill".

**Comment by evancz** [comment]
@burabure, don't get too caught up in this distinction. Making the preview work with changing links (not just in the hash) is going to be hard and I don't think it's worth it. The other way, making a "contextualizer" will solve this and other problems without making the preview page have weird behavior.

**Comment by burabure** [comment]
Tried a couple solutions over the weekend and found a promising one. The hard part was figuring a good way to handle cases where the type anotation is in the same package but another module.

I'll be working in the implementation and send the PR on the next days =)

**Comment by burabure** [comment]
@evancz @jvoigtlaender I've got the basic implementation working here https://github.com/elm-lang/package.elm-lang.org/compare/master...burabure:master

The main idea is to provide a context to the type linking logic with the current module being viewed (this enables us to jump to anchors on the same module easily) and the available definitions (so it can restrict the type definitions we can link to).

It works really well on the UX side, but I would love to hear your impressions before sending the PR; I'm especially sceptic about the clarity of the data structures and the flow of the context.

**Comment by evancz** [comment]
The big thing would be that I have been doing a bunch of work in the `diffs` branch that probably won't merge well with this.

I needed to be able to show types without any styling at all. No colors, no links. It's still in the same file. If you switch over to that branch you can check it out. All the changes are to the "overview" pages, so a package where the version is not specified.

Let me know if I can give more context. I'm not sure if the styling I need there and the styling you need can be combined? Maybe just put the three needed chunks of info in one thing?

**Comment by evancz** [comment]
Oh, I just realized you'll need some additional data to see the overview page that's not available on the website right now. Put [this JSON file](http://pastebin.com/9QTnx5ys) in `packages/elm-lang/core/history.json` and you'll be able to demo things for the core library only.

**Comment by burabure** [comment]
I'll take a look and try to make a merge during the week!

**Comment by burabure** [comment]
@evancz I've merged the changes here https://github.com/burabure/package.elm-lang.org/tree/diffs

I think the context I've added to https://github.com/burabure/package.elm-lang.org/blob/diffs/src/frontend/Docs/Name.elm could replace the "isNormal" flag, but I decided that it would be better if you take a look at it =)

https://github.com/burabure/package.elm-lang.org/blob/diffs/src/frontend/Page/PackageOverview.elm#L386-L392

PS: the diff feature is looking awesome!!!, it's definetly going to be really useful!

**Comment by evancz** [comment]
@burabure, not sure if you saw [this](https://groups.google.com/forum/#!topic/elm-dev/FFN1Ul-E-wM) but it outlines how to get the diff stuff going. I think it makes sense to finish that feature before fixing all the links. One thing to consider is that maybe it'd be good to have links in this page, but have them point to the relevant things. Like, `foo` was added, so it links to the new docs. `blah` was removed so it links to the old ones. When there's a change, you get a link to both old and new.

**Comment by burabure** [comment]
Nice! If we want to be able to link to different versions on the same page the context that I'm using on my fork will probably help. I'll work on that and report back =)

**Pull request merged**
