### PR TITLE
Don't use low res PNG for displaying text.

### PR DESCRIPTION
**Pull request by zigomir**
I haven't took the time and actually run this on my computer because unfortunately I don't know how to do it. I'd be glad to add this section to readme if someone can give me direction.

Anyway, `logo-name.png` looks pretty bad on retina displays so I'm doing this PR to use html instead.

### CODE REVIEW

**Comment by evancz** [comment]
Can you show me a picture of this? I couldn't figure out how to do this without flexbox, and I wasn't sure how far back flexbox is supported on different browsers. Do you know?

**Comment by evancz** [comment]
Also, getting it set up can be super hard, lets just focus on the compatibility question. I tried not to use flexbox because I wanted to be conservative.

**Comment by zigomir** [comment]
Flexbox support is pretty good. Around [95%](http://caniuse.com/#search=flex) according to caniuse. Sorry I haven't write about it in the first place.

Comparison

png
html

**Comment by evancz** [comment]
Alright, thank you! I have been convinced to use flexbox.

**Pull request merged**
